### PR TITLE
update the MLPF model

### PR DESCRIPTION
**Pull request by jpata**
Accompanying the PR https://github.com/cms-sw/cmssw/pull/36841, we update the MLPF model file. No physics changes in standard workflows are expected.

### CODE REVIEW

**Comment by clacaputo** [comment]
@cmsbuild please test

**Comment by perrotta** [comment]
@jpata would you mind signing this one also?
By the way, where is the old RecoParticleFlow/PFProducer/data/mlpf/mlpf_2020_11_04.pb file? I don't see it removed in this PR, but probably it should.

**Comment by jpata** [comment]
Correct, we should remove the old file. Is a follow-up OK?

**Comment by perrotta** [comment]
> Correct, we should remove the old file. Is a follow-up OK?

This won't require other signature than your own: please do it now.
Then this and the accompanying PR can be merged together.

**Comment by jpata** [comment]
please test

**Comment by jpata** [comment]
please abort

**Comment by perrotta** [comment]
please abort

**Comment by perrotta** [comment]
please test with #36841

**Comment by perrotta** [comment]
@smuzaffar I think the tests are stuck...
Is there anything to fix, or should I just try restarting them?

**Comment by smuzaffar** [comment]
please test with cms-sw/cmssw#36841

@perrotta  note the correct cmssw PR name :-)

**Comment by perrotta** [comment]
Ops...
Thank you @smuzaffar !

**Comment by perrotta** [comment]
@jpata can you sign as soon as you want to notify us that you are happy with the data PR?

**Comment by jpata** [comment]
+reconstruction
- tested in https://github.com/cms-sw/cmssw/pull/36841
- remove the old TF model, add the new ONNX model

**Comment by smuzaffar** [comment]
+externals

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
