### PR TITLE
Translated BDT weight files to xml and gzipped them

### PR DESCRIPTION
**Pull request by guitargeek**
Hi,

in the discussions to PR https://github.com/cms-sw/cmssw/pull/24432 we decided to put the weight files translated to XML in the cms-data repository.

Using exclusively the XML format for BDTs in CMSSW saves us from maintaining different parsers for both the text based and XML format, while losing no information whatsoever.

Depends on https://github.com/cms-sw/cmssw/pull/24432 because right now CMSSW would not be able to detect the gzip.

Jonas

### CODE REVIEW

**Comment by slava77** [comment]
@guitargeek 
I was looking at the file sizes (from what I see in the browser), and it seems like xml.gz files are only about a factor of 3 smaller.
I'd naively expect order of a factor of 10 for regular (mostly numerical) txt -> txt.gz.
Is there some significant overhead from txt -> xml conversion? I just wanted to double-check that all of the new file is actually used.

**Comment by guitargeek** [comment]
Yes, the XML format is 50 % larger than the old text based format. I never said the XML files are the best way to store large BDTs :) Still I think it's good because it's robust and easy to parse.

**Comment by slava77** [comment]
On 9/12/18 5:01 AM, Jonas Rembser wrote:
> Yes, the XML format is 50 % larger than the old text based format. I
> never said the XML files are the best way to store large BDTs :) Still I
> think it's good because it's robust and easy to parse.
> 
> —

is it due to the XML overhead (where each subnode perhaps need to have a
specified string name)?
I just want to make sure that it's not from some documentation lines or
figures embedded in addition to the useful data.

**Comment by guitargeek** [comment]
Yes it's just the XML overhead. And not only does every Node have to have a name, but also every attribute needs a name and every attribute needs to be enclosed in braces. In the text format, some attributes could be decoded just by their position in the line without any name.

For example, a node in the text format:
```
0 s seq: 0 ivar: 12 cut: 0.0749741 cType: 0 s: 26000 b: 40000 nEv: 66000 suw: 26000 buw: 40000 nEvuw: 66000 sepI: 0.238751 sepG: 4269.19 nType: 0
```

Here the same node as XML:

```
<Node Cut="0.0749741" IVar="12" b="40000" buw="40000" cType="0" depth="0" nEv="66000" nEvuw="66000" nType="0" pos="s" s="26000" sepG="4269.19" sepI="0.238751" seq="0" suw="26000">
```
The also about 50 % longer line per node is in good agreement with the overall file size increase.

**Comment by guitargeek** [comment]
Here again the script I wrote for the conversion:

https://gist.github.com/guitargeek/a00c86ffd697c8c8aac5e6797a352a3c

**Comment by slava77** [comment]
@smuzaffar, @gudrutis, @mrodozov
the files introduced in this PR were already tested as a part of cms-sw/cmssw#24432 
(the cmssw PR will need to be updated/rebased to remove the bin files commits).

So, I think that we can proceed with merging this and making a cmsdist PR to complete the loop of tests this time with the files appropriately placed in the external.
Please check and merge if there are no issue.
Thank you.

**Pull request merged**
