### PR TITLE
add MLPF weight file

### PR DESCRIPTION
**Pull request by jpata**
Needed for https://github.com/cms-sw/cmssw/pull/32048.

### CODE REVIEW

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#32048

**Comment by jpata** [comment]
please cancel

(I need to update the other PR too, there will be a new workflow)

**Comment by mrodozov** [comment]
abort

**Comment by mrodozov** [comment]
anyway, when it's ready you know how to start them both

**Comment by jpata** [comment]
yes, thank you.

**Comment by slava77** [comment]
some README.md in mlpf/ or even in the main directory would be nice to summarize how the file was made and where it can be used.

**Comment by makortel** [comment]
@silviodonato @qliphy This PR should probably be merged following the merge of https://github.com/cms-sw/cmssw/pull/32048. The workflow added in #32048 (11834.13) is failing in IBs with
```
----- Begin Fatal Exception 05-Jan-2021 19:05:25 CET-----------------------
An exception of category 'FileInPathError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=MLPFProducer label='mlpfProducer'
Exception Message:
edm::FileInPath unable to find file RecoParticleFlow/PFProducer/data/mlpf/mlpf_2020_11_04.pb anywhere in the search path.
```

**Comment by qliphy** [comment]
@makortel   Thanks for pointing this out.
@jpata  Do you think this PR can be ready soon?

**Comment by jpata** [comment]
yes, this may be merged, sorry for not updating the PR description earlier.

**Comment by qliphy** [comment]
merge

**Comment by qliphy** [comment]
to fix the IB failure.  Let's know if there is any concern from missing signatures.

**Pull request merged**
